export const customers = [
  { id: 1, name: '曹嘉玲', avatar: '曹', phone: '13812345678', policyNumber: '882024040101', remark: '近期有意向购买重疾险，下周二下午有空面谈。', gender: 'F', age: 32, maritalStatus: '已婚', birthday: '1994-02-26', daysToBirthday: 3, customerType: '寿险客户', temperature: '高温', value: 'A1', vipLevel: '铂金', serviceLevel: '康养会员', familyMembers: [{ relationship: '配偶', name: '曹雪芹', age: 34, phone: '138****8888' }, { relationship: '女儿', name: '小曹', age: 5, phone: '-' }], address: '深圳市南山区科技园南区', latitude: 22.531, longitude: 113.942 },
  { id: 2, name: '常弘', avatar: '常', phone: '13911012345', policyNumber: '882024040102', remark: '', gender: 'M', age: 45, maritalStatus: '已婚', birthday: '1981-02-12', customerType: '准客', temperature: '中温', value: 'B', vipLevel: '黄金V1', serviceLevel: '居家会员', familyMembers: [{ relationship: '配偶', name: '王芳', age: 42, phone: '139****7777' }], address: '深圳市福田区中心区', latitude: 22.543, longitude: 114.057 },
  { id: 3, name: '常惠', avatar: '常', phone: '13788889999', policyNumber: '882024040103', remark: '已购买意外险，考虑为孩子补充教育金。', gender: 'F', age: 42, maritalStatus: '已婚', birthday: '1984-03-23', daysToBirthday: 0, customerType: '用户', temperature: '低温', value: 'C', vipLevel: '白银', serviceLevel: '', familyMembers: [{ relationship: '儿子', name: '常小明', age: 10, phone: '-' }], address: '深圳市南山区后海片区', latitude: 22.525, longitude: 113.935 },
  { id: 4, name: '陈昌福', avatar: '陈', remark: '', gender: 'M', age: 55, maritalStatus: '已婚', birthday: '1971-02-05', customerType: '寿险客户', temperature: '冷却', value: 'F', vipLevel: '', serviceLevel: '安有护会员', address: '深圳市宝安区新安街道', latitude: 22.555, longitude: 113.893 },
  { id: 5, name: '陈晨', avatar: '陈', remark: '高净值客户，对养老社区感兴趣。', gender: 'F', age: 28, maritalStatus: '未婚', birthday: '1998-08-19', customerType: '寿险客户', temperature: '高温', value: 'A2', vipLevel: '黑钻', serviceLevel: '家办会员', address: '深圳市南山区华侨城', latitude: 22.538, longitude: 113.988 },
  { id: 6, name: '城东', avatar: '城', remark: '', gender: 'M', age: 36, maritalStatus: '已婚', birthday: '1990-03-29', daysToBirthday: 6, customerType: '准客', temperature: '中温', value: 'D', vipLevel: '黄金V2', serviceLevel: '', address: '深圳市龙岗区坂田街道', latitude: 22.623, longitude: 114.043 },
  { id: 7, name: '程钰', avatar: '程', remark: '', gender: 'F', age: 30, maritalStatus: '未婚', birthday: '1996-01-14', customerType: '用户', temperature: '冷却', value: 'E', vipLevel: '', serviceLevel: '', address: '深圳市龙华区民治街道', latitude: 22.658, longitude: 114.025 },
  { id: 8, name: '程钰彤', avatar: '程', badge: '未满14岁', remark: '家长代为咨询，需提供少儿险方案。', gender: 'F', age: 12, maritalStatus: '未婚', birthday: '2014-07-22', customerType: '准客', temperature: '高温', value: 'A4', vipLevel: '白银', serviceLevel: '', address: '深圳市南山区蛇口街道', latitude: 22.482, longitude: 113.925 },
  { id: 9, name: '程指岩', avatar: 'https://picsum.photos/seed/bird/100/100', isImage: true, remark: '', gender: 'M', age: 40, maritalStatus: '已婚', birthday: '1986-10-30', customerType: '寿险客户', temperature: '低温', value: 'A3', vipLevel: '铂金', serviceLevel: '居家会员', address: '深圳市福田区车公庙', latitude: 22.548, longitude: 114.032 },
  { id: 10, name: '曹雪芹', avatar: '曹', remark: '文学爱好者，近期咨询了年金险。', gender: 'M', age: 48, maritalStatus: '已婚', birthday: '1978-05-15', customerType: '寿险客户', temperature: '中温', value: 'A2', vipLevel: '黄金V2', serviceLevel: '健康管理建议', address: '深圳市罗湖区东门街道', latitude: 22.547, longitude: 114.115 },
];
